version: '3.8'
services:
  web:
    image: php:8.0-apache
    volumes:
      - ./site:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
